cursor #575279
cursor_text_color #575279

foreground            #575279
background            #fffaf3
selection_foreground  #faf4ed
selection_background  #ea9d34
url_color             #907aa9

# black
color8   #575279
color0   #4c4c4c

# red
color1   #b4637a
color9   #c49ea0

# green
color2   #575279
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
/* color4  #8f8aac */
color4  #907aa9
color12 #a39ec4

# magenta
color5   #b4637a
color13  #c49ec4

# cyan
color6   #575279
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0