# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D6DEE4
background         #131417
cursor             #757B86

active_tab_foreground     #131417
active_tab_background     #D6DEE4
inactive_tab_foreground   #D6DEE4
inactive_tab_background   #131417

active_border_color   #D6DEE4
inactive_border_color #131417
bell_border_color     #0C0F1B

color0      #3B3B3E
color1		#0C0F1B
color2		#0F121E
color3		#353956
color4		#43486A
color5		#43486B
color6		#687986
color7		#BCC8D0
color8		#848C92
color9		#111424
color10		#151828
color11		#474D73
color12		#59608E
color13		#59608E
color14		#8AA1B2
color15		#BCC8D0
